70322_Lutsko_Sol/70322_Lutsko/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MOVIES_DAL;
using _70322_Lutsko.Models;

namespace _70322_Lutsko.Controllers
{
    public class CartController : Controller
    {
        IRepository<Movie> repository;
        // GET: Cart
        public CartController(IRepository<Movie> repo)
        {
            repository = repo;
        }

        /// <summary> 
        /// Получение корзины из сессии ]
        /// </summary>]
        /// <returns></returns> 
        /// 
        public Cart GetCart()
        {
            Cart cart = Session["сart"] as Cart;
            if (cart == null)
            {
                cart = new Cart();
                Session["сart"] = cart;
            }
            return cart;
        }

        [Authorize]
        public ActionResult Index(string returnUrl)
        {
            TempData["returnUrl"] = returnUrl;
            return View(GetCart());
        }

        /// <summary> 
        /// Добавление товара в корзину
        /// </summary> 
        /// <param name="id">id добавляемого элемента</param> 
        /// <param name="returnUrl">URL страницы для возврата</param>
        /// <returns></returns>
        public RedirectResult AddToCart(int id, string returnUrl)
        {
            var item = repository.Get(id);
            if (item != null)
            {
                GetCart().AddItem(item);
                ViewBag.MessageCart = string.Format("Успешно добавлен элемент: {0}", item.MovieName);
            }
            ViewBag.MessageCart = "Элемент не был добавлен";
            return Redirect(returnUrl);
        }

        //Вывод общей информации о корзине в заголовке страницы
        public PartialViewResult CartSummary(string returnUrl)
        {
            TempData["returnUrl"] = returnUrl;
            return PartialView(GetCart());
        }
    }
}

70322_Lutsko_Sol/70322_Lutsko/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MOVIES_DAL;
using _70322_Lutsko.Models;

namespace _70322_Lutsko.Controllers
{
    public class InfoController : Controller
    {
        readonly int pageSize = 3;

        IRepository<Movie> repository;
            public InfoController(IRepository<Movie> repo)
            {
                repository = repo;
            }
        // GET: Info
        public ActionResult Index(string group, int page = 1)
        {
            var lst = repository.GetAll()
                .Where(d => group == null
                || d.GroupName.Equals(group));
                
            var model = PageListViewModel<Movie>.CreatePage(lst, page, pageSize);
            if (Request.IsAjaxRequest())
            {
                return PartialView("ListPartial", model);
            }
            return View(model);
        }
        public FileContentResult GetImage(int id)
        {
            var movie = repository.Get(id);
            if (movie != null)
            {
                return new FileContentResult(movie.Image, movie.MimeType);
            }
            else return null;
        }
    }
}

70322_Lutsko_Sol/70322_Lutsko/Controllers/MenuController.cs
using _70322_Lutsko.Models;
using MOVIES_DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _70322_Lutsko.Controllers
{

    public class MenuController : Controller
    {
        private List<MenuItem> items;
        IRepository<Movie> repository;

        public MenuController(IRepository<Movie> repo)
        {
            repository = repo;
            items = new List<MenuItem>
            {
                new MenuItem{Name="Домой", Controller="Home",
                Action="Index", Active=string.Empty},
                new MenuItem{Name="Cписок фильмов", Controller="Info",
                Action="Index", Active=string.Empty},
                new MenuItem{Name="Администрирование", Controller="Admin",
                Action="Index", Active=string.Empty},
            };
        }

        public PartialViewResult Main(string a = "Index", string c = "Home")
        {
            if (items.Where(t => t.Controller == c).Count() > 0)
            {
                items.First(m => m.Controller == c).Active = "active";
            }
            return PartialView(items);
        }
        public PartialViewResult UserInfo()
        {
            return PartialView();
        }
        public PartialViewResult Side()
        {

            var groups = repository.GetAll()
            .Select(d => d.GroupName)
            .Distinct();


            var x = groups.ToList();


            return PartialView(groups);
        }
        public PartialViewResult Map(string a = "Index", string c = "Home")
        {
            items.First(m => m.Controller == c).Active = "active"; return PartialView(items);
        }
        // GET: Menu
        public ActionResult Index()
        {
          return View();
        }

    }
   
}

70322_Lutsko_Sol/70322_Lutsko/Views/Shared/ItemViewPartial.cshtml
@model MOVIES_DAL.Movie

<div class='col-md-4'>
    <div class='thumbnail'>
        <img height="200" src="@Url.Action("getImage",new {id=Model.MovieId })"
             alt='NoImage'
             class="img-thumbnail" />
        <div class="caption">
            <div class="item-name">
                <h3>@Model.MovieName</h3>
            </div>
            <div class="item-description">
                @Model.Description
            </div>
            <div class="centered">
                <h3 class="badge">@Model.Price рублей</h3>
            </div>
            <div class="centered">
                <a href=@Url.Action("AddToCart", "Cart", new {id=Model.MovieId, returnUrl=Request.Path} )
                class="btn btn-primary">
                    <span class="glyphicon glyphicon-shopping-cart">
                    </span>
                    В корзину
                </a>
            </div>
        </div>
    </div>
</div>

70322_Lutsko_Sol/70322_Lutsko/Views/Shared/ListPartial.cshtml
@model _70322_Lutsko.Models.PageListViewModel<MOVIES_DAL.Movie>
@using System.Text;


@{
    // объект для "собирания" разметки
    StringBuilder result = new StringBuilder();
    // счетчик эскизов в строке
    var i = 0;
    TagBuilder row = new TagBuilder("div");
    foreach (var item in Model)
    {
        i++;
        if (i == 1) // для первого элемента в строке создаем новую строку
        {
            row = new TagBuilder("div");
            row.AddCssClass("row");
            row.AddCssClass("item-row");
        }
        row.InnerHtml += Html.Partial("ItemViewPartial", item);
        if (i == 3) // если строка закончена
        {
            // добавить строку в разметку
            result.Append(row.ToString());
        }
    }
    if (i != 3) // если последняя строка не заполнена
    {
        // добавить строку в разметку
        result.Append(row.ToString());
        // обнулить счетчик элементов в строке
        i = 0;
    }
    <!-- Получить готовую разметку --> 
    @MvcHtmlString.Create(result.ToString()) 
    @Html.Partial("PagerPartial", Model)
}

70322_Lutsko_Sol/70322_Lutsko/Views/Shared/PagerPartial.cshtml
@model _70322_Lutsko.Models.PageListViewModel<MOVIES_DAL.Movie>
@using System.Text
@{
    var groupName = Request.RequestContext.RouteData.Values["group"];
    var result = new StringBuilder();
    // стрелка влево
    var liPrevNext = new TagBuilder("li");
    liPrevNext.InnerHtml = Ajax.ActionLink("<<", "Index",
        new {
            group = groupName,
            page = Model.CurrentPage - 1
        },
         new AjaxOptions
         {
             InsertionMode = InsertionMode.Replace,
             UpdateTargetId = "Index"
         })
    .ToString();
    if (Model.CurrentPage == 1)
    {
        liPrevNext.AddCssClass("disabled");
    }
    result.Append(liPrevNext.ToString());
    // пейджер
    for (int i = 1; i <= Model.TotalPages; i++)
    {
        var li = new TagBuilder("li");
        if (i == Model.CurrentPage)
        {
            li.AddCssClass("active");

        }
        li.InnerHtml = Ajax.RouteLink(i.ToString(),
    new {
        action = "Index",
        group = groupName,
        page = i },
    new AjaxOptions {
        UpdateTargetId = "Index",
        InsertionMode = InsertionMode.Replace }).ToString();

        result.Append(li.ToString());
    }
    // стрелка вправо
    liPrevNext = new TagBuilder("li");
    liPrevNext.InnerHtml = Ajax.ActionLink(">>", "Index", new
    { group = groupName,
      page = Model.CurrentPage + 1 },
         new AjaxOptions {
             InsertionMode = InsertionMode.Replace,
             UpdateTargetId = "Index" }).ToString();
    if (Model.CurrentPage == Model.TotalPages)
    {
        liPrevNext.AddCssClass("disabled");
    }
    result.Append(liPrevNext.ToString());
     }
<ul class="pagination">
    @MvcHtmlString.Create(result.ToString());
</ul>

70322_Lutsko_Sol/70322_Lutsko/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>


    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <meta charset="utf-8" />


    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!--Заголовок страницы-->
    <div class="header-strip">
        <!--Панель аутентификации-->
        <div class="container">
            @Html.Action("UserInfo", "Menu")
        </div> <!--Панель аутентификации (конец)-->
        <!-- панель навигации-->
        <div class="container">
            <div class="navbar navbar-inverse" role="navigation">
                <div class="logo">
                    <a class="navbar-brand" href="http://localhost:19189/">Люцко</a>
                </div>
                @Html.Action("Main", "Menu", new { c = Request.RequestContext.RouteData.Values["controller"], })
            </div>
        </div><!--панель навигации (конец)-->
    </div><!--Заголовок страницы(конец)-->
    <!--Содержимое сайта-->
    <div class="main-body">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-3">
                    <h2>@ViewBag.MyText</h2>
                </div>
            </div>
            <div class="row">

                <!--Левая боковая панель-->
                <div class="col-md-3">
                    @RenderSection("SidePanel", required: false)
                </div>
                <!--/Левая боковая панель (конец)-->
                <!--Основная панель-->
                <div class="col-md-9">
                    @RenderBody()
                </div>
                <!--/Основная панель (конец)-->

            </div>
        </div><!--Содержимое сайта (конец)-->
    </div>

    <!--Подвал страницы-->
    <div class="footer-strip">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <h6>Kарта сайта</h6>
                    <ul>
                        <li>@Html.ActionLink("Домой", "Index", "Home")</li>
                        <li class="active">
                            @Html.ActionLink("Фильмы", "Index", "Info")
                        </li>
                        <li>@Html.ActionLink("Администрирование", "Index", "Admin")</li>
                    </ul>
                </div>
                <div class="col-md-3 col-md-offset-6">
                    <h6>Социальные сети</h6>
                    <a href="http://vk.com"
                       class="social-icon vk"></a>
                    <a href="http://twitter.com"
                       class="social-icon twitter"></a>
                    <a href="http://facebook.com"
                       class="social-icon facebook"></a>
                </div>
            </div>
        </div>
    </div><!--Подвал страницы (конец)-->


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @section Scripts {
        <script src="~/Scripts/jquery.validate.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.js"></script> }
</body>
</html>